# Form implementation generated from reading ui file 'CISProject2gui.ui'
#
# Created by: PyQt6 UI code generator 6.10.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(779, 543)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.textBrowser = QtWidgets.QTextBrowser(parent=self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(300, 30, 191, 51))
        self.textBrowser.setObjectName("textBrowser")
        self.fullname_lineedit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.fullname_lineedit.setGeometry(QtCore.QRect(120, 109, 131, 21))
        self.fullname_lineedit.setObjectName("fullname_lineedit")
        self.email_lineedit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.email_lineedit.setGeometry(QtCore.QRect(120, 169, 131, 21))
        self.email_lineedit.setObjectName("email_lineedit")
        self.number_lineedit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.number_lineedit.setGeometry(QtCore.QRect(120, 240, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.number_lineedit.setFont(font)
        self.number_lineedit.setObjectName("number_lineedit")
        self.fullname_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.fullname_label.setGeometry(QtCore.QRect(30, 110, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.fullname_label.setFont(font)
        self.fullname_label.setObjectName("fullname_label")
        self.email_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.email_label.setGeometry(QtCore.QRect(70, 170, 47, 13))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.email_label.setFont(font)
        self.email_label.setObjectName("email_label")
        self.number_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.number_label.setGeometry(QtCore.QRect(50, 240, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.number_label.setFont(font)
        self.number_label.setObjectName("number_label")
        self.textEdit = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(120, 340, 511, 61))
        self.textEdit.setObjectName("textEdit")
        self.issue_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.issue_label.setGeometry(QtCore.QRect(180, 300, 391, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.issue_label.setFont(font)
        self.issue_label.setObjectName("issue_label")
        self.submit_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.submit_button.setGeometry(QtCore.QRect(320, 440, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.submit_button.setFont(font)
        self.submit_button.setObjectName("submit_button")
        self.validation_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.validation_label.setGeometry(QtCore.QRect(320, 410, 341, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.validation_label.setFont(font)
        self.validation_label.setText("")
        self.validation_label.setObjectName("validation_label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 779, 21))
        self.menubar.setObjectName("menubar")
        self.menuTicket_Creation = QtWidgets.QMenu(parent=self.menubar)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.menuTicket_Creation.setFont(font)
        self.menuTicket_Creation.setObjectName("menuTicket_Creation")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuTicket_Creation.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:20pt;\">Ticket Creation</span></p></body></html>"))
        self.fullname_label.setText(_translate("MainWindow", "Full Name:"))
        self.email_label.setText(_translate("MainWindow", "Email:"))
        self.number_label.setText(_translate("MainWindow", "Number:"))
        self.issue_label.setText(_translate("MainWindow", "Descibe the issue that is going on below:"))
        self.submit_button.setText(_translate("MainWindow", "Submit"))
        self.menuTicket_Creation.setTitle(_translate("MainWindow", "Ticket Creation"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
