# Form implementation generated from reading ui file 'newCISProject1gui.ui'
#
# Created by: PyQt6 UI code generator 6.10.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(455, 337)
        MainWindow.setMinimumSize(QtCore.QSize(455, 337))
        MainWindow.setMaximumSize(QtCore.QSize(455, 337))
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.vote_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.vote_button.setGeometry(QtCore.QRect(90, 250, 75, 23))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.vote_button.setFont(font)
        self.vote_button.setObjectName("vote_button")
        self.exit_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.exit_button.setGeometry(QtCore.QRect(280, 250, 75, 23))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.exit_button.setFont(font)
        self.exit_button.setObjectName("exit_button")
        self.jerald_button = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.jerald_button.setGeometry(QtCore.QRect(340, 180, 161, 17))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.jerald_button.setFont(font)
        self.jerald_button.setObjectName("jerald_button")
        self.voteGroup = QtWidgets.QButtonGroup(MainWindow)
        self.voteGroup.setObjectName("voteGroup")
        self.voteGroup.addButton(self.jerald_button)
        self.corey_button = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.corey_button.setGeometry(QtCore.QRect(200, 180, 82, 17))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.corey_button.setFont(font)
        self.corey_button.setObjectName("corey_button")
        self.voteGroup.addButton(self.corey_button)
        self.bob_button = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.bob_button.setGeometry(QtCore.QRect(80, 180, 82, 17))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.bob_button.setFont(font)
        self.bob_button.setObjectName("bob_button")
        self.voteGroup.addButton(self.bob_button)
        self.name_field = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.name_field.setGeometry(QtCore.QRect(140, 110, 211, 20))
        self.name_field.setObjectName("name_field")
        self.textBrowser = QtWidgets.QTextBrowser(parent=self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(130, 10, 221, 41))
        self.textBrowser.setObjectName("textBrowser")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(90, 110, 47, 13))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_validation = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_validation.setGeometry(QtCore.QRect(130, 220, 231, 16))
        self.label_validation.setText("")
        self.label_validation.setObjectName("label_validation")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 455, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.vote_button.setText(_translate("MainWindow", "Vote"))
        self.exit_button.setText(_translate("MainWindow", "Exit"))
        self.jerald_button.setText(_translate("MainWindow", "Jerald"))
        self.corey_button.setText(_translate("MainWindow", "Corey"))
        self.bob_button.setText(_translate("MainWindow", "Bob"))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:20pt;\">Candidate Menu</span></p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "Name:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
